

set -g mouse on

# Change leader key to C-n 
set -g prefix C-b

set -sg escape-time 10
setw -g mode-keys vi

# Status Bar
set -g status-style "fg=default"
set -g status-bg default
set -g status-position top
set -g status-justify absolute-centre
set -g status-interval 10
set -g window-status-current-style "fg=blue bold"
set -g status-left ""
# So that when new windows are always created at the last index
set -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'christoomey/vim-tmux-navigator'


bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
# bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"


# Max number of lines on the scrollback
set -g history-limit 100000


# set-option -g default-shell /usr/bin/zsh
set-option -g default-shell /bin/zsh

# Prevent scrol down when yanking text
set -g @yank_action "copy-pipe"

set-option -g set-clipboard on


# Put the homebrew installed apps at the PATH
set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin"

# Jump to previous/next shell prompt in copy mode
bind -T copy-mode-vi 'K' send -X search-backward "➜  ~"
bind -T copy-mode-vi 'J' send -X search-forward "➜  ~"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
